"""add connections table

Revision ID: ba18e3d4f201
Revises: f1d275d7eb7e
Create Date: 2025-05-22 17:30:06.389610

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "ba18e3d4f201"
down_revision = "f1d275d7eb7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connection",
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("source_user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("target_user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "full_name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("connection")
    # ### end Alembic commands ###
